### ISSUE TITLE
asdu_resp object has no causa_tm attribute.

### ISSUE THREAD

**Issue by mstfbirinci** [javierdelapuente/reeprotocol#5]
Sometimes when I trying to read data from meters points, I got an exception: asdu_resp object has no causa_tm attribute. 

Why this exception can be caused? You also mention that in protocol.py:

""" this function makes a very ugly assumption,
     if you don't iterate over all elements, the program will fail"""

**Comment by javierdelapuente** [comment]
I made some changes 15 days ago that could fix your problem. 

Please check it. If it does not work, could you share logs, sent and received bytes so we could check?
